- hosts: server
  remote_user: ubuntu
  become: Yes
  tasks:
    - name: install docker
      apt:
        name:
          - docker
          - docker-compose
        state: present
    - name: login docker hub
      shell: echo {{DOCKER_PASSWORD}} | docker login --username {{DOCKER_USERNAME}} --password-stdin"
    - name: coppy file
      copy:
        src: docker-compose.yaml
        dest: /home/ubuntu
    - name: restart docker-compose
      shell: |
        docker-compose stop
        docker-compose rm -f
        docker-compose pull
        docker-compose up -d