- hosts: server
  remote_user: ubuntu
  become: Yes
  tasks:
    - name: install docker
      apt:
        name:
          - docker
          - docker-compose
        state: present
    - name: login docker hub
      docker login -u "{{DOCKER_USERNAME}}" -p "{{DOCKER_PASSWORD}}"
    - name: coppy file
      coppy:
        src: docker-compose.yaml
        desk: /home/ubuntu
    - name: restart docker-compose
      shell: |
        docker-compose stop
        docker-compose rm -f
        docker-compose pull
        docker-compose up -d